--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "auth_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" integer NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
--
-- Alter field action_time on logentry
--
-- (no-op)
--
-- Alter field action_flag on logentry
--
-- (no-op)
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name";
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
--
-- Alter field email on user
--
ALTER TABLE "auth_user" ALTER COLUMN "email" TYPE varchar(254);
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field last_login on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_login" DROP NOT NULL;
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field username on user
--
ALTER TABLE "auth_user" ALTER COLUMN "username" TYPE varchar(150);
--
-- Alter field last_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_name" TYPE varchar(150);
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Alter field first_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "first_name" TYPE varchar(150);
--
-- Create model City
--
CREATE TABLE "myapp_city" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model HeroVideo
--
CREATE TABLE "myapp_herovideo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(120) NOT NULL, "video" varchar(100) NULL, "poster" varchar(100) NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model Package
--
CREATE TABLE "myapp_package" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(150) NOT NULL, "category" varchar(20) NOT NULL, "price" numeric(12, 0) NOT NULL, "old_price" numeric(12, 0) NULL, "description" text NOT NULL, "thumbnail" varchar(100) NULL, "photographers" integer NOT NULL CHECK ("photographers" >= 0), "videographers" integer NOT NULL CHECK ("videographers" >= 0), "hours" integer NOT NULL CHECK ("hours" >= 0), "edited_photos" integer NOT NULL CHECK ("edited_photos" >= 0), "reels" integer NOT NULL CHECK ("reels" >= 0), "cinematic_film" boolean NOT NULL, "album" boolean NOT NULL, "drone" boolean NOT NULL, "full_day_coverage" boolean NOT NULL, "same_day_edit" boolean NOT NULL, "deliverables" text NOT NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model PortfolioCategory
--
CREATE TABLE "myapp_portfoliocategory" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model Service
--
CREATE TABLE "myapp_service" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(120) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "icon_key" varchar(60) NOT NULL, "tagline" varchar(180) NOT NULL, "short_description" varchar(220) NOT NULL, "description" text NOT NULL, "image" varchar(100) NULL, "video" varchar(100) NULL, "video_poster" varchar(100) NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model SiteSettings
--
CREATE TABLE "myapp_sitesettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "brand_name" varchar(120) NOT NULL, "tagline" varchar(200) NOT NULL, "site_description" text NOT NULL, "phones" varchar(200) NOT NULL, "whatsapp_number" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "address" varchar(300) NOT NULL, "instagram" varchar(200) NOT NULL, "facebook" varchar(200) NOT NULL, "youtube" varchar(200) NOT NULL, "home_hero_title" varchar(200) NOT NULL, "home_hero_subtitle" varchar(300) NOT NULL, "years_experience" integer NOT NULL CHECK ("years_experience" >= 0), "events_shot" integer NOT NULL CHECK ("events_shot" >= 0), "happy_clients" integer NOT NULL CHECK ("happy_clients" >= 0), "hero_fallback" varchar(100) NULL);
--
-- Create model TeamMember
--
CREATE TABLE "myapp_teammember" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(120) NOT NULL, "role" varchar(120) NOT NULL, "photo" varchar(100) NULL, "bio" text NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model Testimonial
--
CREATE TABLE "myapp_testimonial" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "client_name" varchar(120) NOT NULL, "client_photo" varchar(100) NULL, "event_type" varchar(120) NOT NULL, "city" varchar(120) NOT NULL, "rating" smallint NOT NULL CHECK ("rating" >= 0), "review" text NOT NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0), "created_at" timestamp with time zone NOT NULL);
--
-- Create model PackageFeature
--
CREATE TABLE "myapp_packagefeature" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "label" varchar(140) NOT NULL, "value" varchar(140) NOT NULL, "package_id" bigint NOT NULL);
--
-- Create model PortfolioImage
--
CREATE TABLE "myapp_portfolioimage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "description" text NOT NULL, "image" varchar(100) NOT NULL, "alt_text" varchar(200) NOT NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0), "created_at" timestamp with time zone NOT NULL, "category_id" bigint NULL);
--
-- Create model PortfolioVideo
--
CREATE TABLE "myapp_portfoliovideo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "video" varchar(100) NULL, "youtube_url" varchar(200) NOT NULL, "poster" varchar(100) NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0), "created_at" timestamp with time zone NOT NULL, "category_id" bigint NULL);
--
-- Add field services to package
--
CREATE TABLE "myapp_package_services" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "package_id" bigint NOT NULL, "service_id" bigint NOT NULL);
--
-- Create model Offer
--
CREATE TABLE "myapp_offer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "title" varchar(180) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "description" text NOT NULL, "included_services" text NOT NULL, "original_price" numeric(12, 0) NOT NULL, "offer_price" numeric(12, 0) NOT NULL, "start_date" date NULL, "end_date" date NULL, "image" varchar(100) NULL, "video" varchar(100) NULL, "is_featured" boolean NOT NULL, "is_active" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
CREATE TABLE "myapp_offer_services" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "offer_id" bigint NOT NULL, "service_id" bigint NOT NULL);
--
-- Create model Enquiry
--
CREATE TABLE "myapp_enquiry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "event_date" date NULL, "city" varchar(120) NOT NULL, "budget" varchar(30) NOT NULL, "message" text NOT NULL, "status" varchar(20) NOT NULL, "notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "service_id" bigint NULL);
CREATE INDEX "myapp_city_name_f3b21296_like" ON "myapp_city" ("name" varchar_pattern_ops);
CREATE INDEX "myapp_package_category_8ab3558c" ON "myapp_package" ("category");
CREATE INDEX "myapp_package_category_8ab3558c_like" ON "myapp_package" ("category" varchar_pattern_ops);
CREATE INDEX "myapp_portfoliocategory_slug_92e1a59d_like" ON "myapp_portfoliocategory" ("slug" varchar_pattern_ops);
CREATE INDEX "myapp_service_slug_1e41bf9c_like" ON "myapp_service" ("slug" varchar_pattern_ops);
ALTER TABLE "myapp_packagefeature" ADD CONSTRAINT "myapp_packagefeature_package_id_7f17a030_fk_myapp_package_id" FOREIGN KEY ("package_id") REFERENCES "myapp_package" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "myapp_packagefeature_package_id_7f17a030" ON "myapp_packagefeature" ("package_id");
ALTER TABLE "myapp_portfolioimage" ADD CONSTRAINT "myapp_portfolioimage_category_id_35d0a521_fk_myapp_por" FOREIGN KEY ("category_id") REFERENCES "myapp_portfoliocategory" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "myapp_portfolioimage_category_id_35d0a521" ON "myapp_portfolioimage" ("category_id");
ALTER TABLE "myapp_portfoliovideo" ADD CONSTRAINT "myapp_portfoliovideo_category_id_ef38c5ab_fk_myapp_por" FOREIGN KEY ("category_id") REFERENCES "myapp_portfoliocategory" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "myapp_portfoliovideo_category_id_ef38c5ab" ON "myapp_portfoliovideo" ("category_id");
ALTER TABLE "myapp_package_services" ADD CONSTRAINT "myapp_package_services_package_id_service_id_4f6a89aa_uniq" UNIQUE ("package_id", "service_id");
ALTER TABLE "myapp_package_services" ADD CONSTRAINT "myapp_package_services_package_id_8aa9ec69_fk_myapp_package_id" FOREIGN KEY ("package_id") REFERENCES "myapp_package" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "myapp_package_services" ADD CONSTRAINT "myapp_package_services_service_id_029e9529_fk_myapp_service_id" FOREIGN KEY ("service_id") REFERENCES "myapp_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "myapp_package_services_package_id_8aa9ec69" ON "myapp_package_services" ("package_id");
CREATE INDEX "myapp_package_services_service_id_029e9529" ON "myapp_package_services" ("service_id");
CREATE INDEX "myapp_offer_slug_06cef558_like" ON "myapp_offer" ("slug" varchar_pattern_ops);
ALTER TABLE "myapp_offer_services" ADD CONSTRAINT "myapp_offer_services_offer_id_service_id_3d456e73_uniq" UNIQUE ("offer_id", "service_id");
ALTER TABLE "myapp_offer_services" ADD CONSTRAINT "myapp_offer_services_offer_id_a7a48599_fk_myapp_offer_id" FOREIGN KEY ("offer_id") REFERENCES "myapp_offer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "myapp_offer_services" ADD CONSTRAINT "myapp_offer_services_service_id_052212d5_fk_myapp_service_id" FOREIGN KEY ("service_id") REFERENCES "myapp_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "myapp_offer_services_offer_id_a7a48599" ON "myapp_offer_services" ("offer_id");
CREATE INDEX "myapp_offer_services_service_id_052212d5" ON "myapp_offer_services" ("service_id");
ALTER TABLE "myapp_enquiry" ADD CONSTRAINT "myapp_enquiry_service_id_6fe6f309_fk_myapp_service_id" FOREIGN KEY ("service_id") REFERENCES "myapp_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "myapp_enquiry_status_07fd8b02" ON "myapp_enquiry" ("status");
CREATE INDEX "myapp_enquiry_status_07fd8b02_like" ON "myapp_enquiry" ("status" varchar_pattern_ops);
CREATE INDEX "myapp_enquiry_service_id_6fe6f309" ON "myapp_enquiry" ("service_id");
--
-- Add field logo to sitesettings
--
ALTER TABLE "myapp_sitesettings" ADD COLUMN "logo" varchar(100) NULL;
--
-- Alter field brand_name on sitesettings
--
-- (no-op)
--
-- Create model ThemeSettings
--
CREATE TABLE "myapp_themesettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_custom" boolean NOT NULL, "background" varchar(9) NOT NULL, "background_secondary" varchar(9) NOT NULL, "ink" varchar(9) NOT NULL, "ink_secondary" varchar(9) NOT NULL, "ivory" varchar(9) NOT NULL, "ivory_secondary" varchar(9) NOT NULL, "cream" varchar(9) NOT NULL, "primary" varchar(9) NOT NULL, "primary_strong" varchar(9) NOT NULL, "primary_deep" varchar(9) NOT NULL, "muted" varchar(9) NOT NULL, "muted_secondary" varchar(9) NOT NULL, "heading_font" varchar(200) NOT NULL, "body_font" varchar(200) NOT NULL, "container_width" integer NOT NULL CHECK ("container_width" >= 0));
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
--
-- Create model Site
--
CREATE TABLE "django_site" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "domain" varchar(100) NOT NULL, "name" varchar(50) NOT NULL);
--
-- Alter field domain on site
--
ALTER TABLE "django_site" ADD CONSTRAINT "django_site_domain_a2e37b91_uniq" UNIQUE ("domain");
CREATE INDEX "django_site_domain_a2e37b91_like" ON "django_site" ("domain" varchar_pattern_ops);

-- ====================================================================
-- Django migration history (marks every migration as applied so that a
-- later `manage.py migrate` no-ops instead of re-running the DDL).
-- ====================================================================
CREATE TABLE "django_migrations" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "app" varchar(255) NOT NULL,
    "name" varchar(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES
('contenttypes', '0001_initial', now()),
('auth', '0001_initial', now()),
('admin', '0001_initial', now()),
('admin', '0002_logentry_remove_auto_add', now()),
('admin', '0003_logentry_add_action_flag_choices', now()),
('contenttypes', '0002_remove_content_type_name', now()),
('auth', '0002_alter_permission_name_max_length', now()),
('auth', '0003_alter_user_email_max_length', now()),
('auth', '0004_alter_user_username_opts', now()),
('auth', '0005_alter_user_last_login_null', now()),
('auth', '0006_require_contenttypes_0002', now()),
('auth', '0007_alter_validators_add_error_messages', now()),
('auth', '0008_alter_user_username_max_length', now()),
('auth', '0009_alter_user_last_name_max_length', now()),
('auth', '0010_alter_group_name_max_length', now()),
('auth', '0011_update_proxy_permissions', now()),
('auth', '0012_alter_user_first_name_max_length', now()),
('myapp', '0001_initial', now()),
('myapp', '0002_sitesettings_logo_alter_sitesettings_brand_name', now()),
('myapp', '0003_themesettings', now()),
('sessions', '0001_initial', now()),
('sites', '0001_initial', now()),
('sites', '0002_alter_domain_unique', now());
