# Generated by Django 6.1 on 2026-08-09 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('video', models.FileField(blank=True, help_text='MP4 recommended.', null=True, upload_to='hero/')),
                ('poster', models.ImageField(blank=True, help_text='Shown until video loads.', null=True, upload_to='hero/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hero videos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('affordable', 'Affordable'), ('classic', 'Classic'), ('premium', 'Premium'), ('luxury', 'Luxury')], db_index=True, default='classic', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('photographers', models.PositiveIntegerField(default=1)),
                ('videographers', models.PositiveIntegerField(default=0)),
                ('hours', models.PositiveIntegerField(default=8)),
                ('edited_photos', models.PositiveIntegerField(default=0)),
                ('reels', models.PositiveIntegerField(default=0, help_text='Set 0 to hide this row.')),
                ('cinematic_film', models.BooleanField(default=False)),
                ('album', models.BooleanField(default=False)),
                ('drone', models.BooleanField(default=False)),
                ('full_day_coverage', models.BooleanField(default=False)),
                ('same_day_edit', models.BooleanField(default=False)),
                ('deliverables', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Portfolio categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon_key', models.CharField(blank=True, help_text='e.g. wedding, prewedding, engagement, couple, maternity, baby', max_length=60)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('video', models.FileField(blank=True, null=True, upload_to='services/')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='services/posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Lumivue Studio', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Photography & Cinematography', max_length=200)),
                ('site_description', models.TextField(blank=True, default='Premium photography & videography studio crafting timeless wedding, pre-wedding, engagement, maternity and baby stories across every city.')),
                ('phones', models.CharField(blank=True, default='+91 98765 43210', help_text='Comma separated numbers.', max_length=200)),
                ('whatsapp_number', models.CharField(default='919876543210', help_text='Include country code, digits only.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('home_hero_title', models.CharField(default='Every love story is a film waiting to be made.', max_length=200)),
                ('home_hero_subtitle', models.CharField(default='Timeless wedding, pre-wedding, maternity and baby stories — shot across every city.', max_length=300)),
                ('years_experience', models.PositiveIntegerField(default=8)),
                ('events_shot', models.PositiveIntegerField(default=600, verbose_name='Events shot')),
                ('happy_clients', models.PositiveIntegerField(default=900)),
                ('hero_fallback', models.ImageField(blank=True, help_text='Fallback hero image when no video is available.', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('event_type', models.CharField(blank=True, default='Wedding', max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('value', models.CharField(blank=True, max_length=140)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myapp.package')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='myapp.portfoliocategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/videos/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube embed URL if not uploading a video file.')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='portfolio/posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='myapp.portfoliocategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Show this package on these service pages.', related_name='packages', to='myapp.service'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('included_services', models.TextField(blank=True, help_text='One item per line. Shown as a checklist on the offer card.')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('offer_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('video', models.FileField(blank=True, null=True, upload_to='offers/videos/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('services', models.ManyToManyField(blank=True, related_name='offers', to='myapp.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(choices=[('under_25000', 'Under ₹25,000'), ('25000_50000', '₹25,000 – ₹50,000'), ('50000_100000', '₹50,000 – ₹1,00,000'), ('100000_plus', '₹1,00,000+'), ('luxury', 'Luxury / Custom')], default='under_25000', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the studio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='myapp.service')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
