# Generated by Django 6.1 on 2026-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sitesettings_logo_alter_sitesettings_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_custom', models.BooleanField(default=True, help_text='Apply the custom theme below. Uncheck to use the default design.')),
                ('background', models.CharField(default='#0f0d0c', help_text='Page background', max_length=9)),
                ('background_secondary', models.CharField(default='#141211', help_text='Card / section background', max_length=9)),
                ('ink', models.CharField(default='#1b1816', help_text='Darkest text on light surfaces', max_length=9)),
                ('ink_secondary', models.CharField(default='#221e1a', max_length=9)),
                ('ivory', models.CharField(default='#f4eee2', help_text='Main light text / surface', max_length=9)),
                ('ivory_secondary', models.CharField(default='#ece3d2', max_length=9)),
                ('cream', models.CharField(default='#faf6ef', help_text='Light page backgrounds', max_length=9)),
                ('primary', models.CharField(default='#b28a54', help_text='Brand accent (gold)', max_length=9)),
                ('primary_strong', models.CharField(default='#d9bd8b', help_text='Bright accent (hover)', max_length=9)),
                ('primary_deep', models.CharField(default='#8f6a3f', help_text='Deep accent', max_length=9)),
                ('muted', models.CharField(default='#b7a98f', help_text='Muted text', max_length=9)),
                ('muted_secondary', models.CharField(default='#7c7161', help_text='Fainter text', max_length=9)),
                ('heading_font', models.CharField(choices=[("'Playfair Display', Georgia, serif", 'Playfair Display'), ("'Cormorant Garamond', Georgia, serif", 'Cormorant Garamond'), ("'Marcellus', Georgia, serif", 'Marcellus'), ("'Libre Baskerville', Georgia, serif", 'Libre Baskerville'), ("'EB Garamond', Georgia, serif", 'EB Garamond')], default="'Playfair Display', Georgia, serif", max_length=200)),
                ('body_font', models.CharField(choices=[("Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Manrope'), ('Poppins, -apple-system, BlinkMacSystemFont, sans-serif', 'Poppins'), ('Inter, -apple-system, BlinkMacSystemFont, sans-serif', 'Inter'), ('Jost, -apple-system, BlinkMacSystemFont, sans-serif', 'Jost'), ("'Nunito Sans', -apple-system, BlinkMacSystemFont, sans-serif", 'Nunito Sans')], default="Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", max_length=200)),
                ('container_width', models.PositiveIntegerField(default=1180, help_text='Max content width in px')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
