# Generated by Django 6.1 on 2026-08-11 18:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_themesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 recommended.', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='offers/videos/'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='portfolio/videos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='services/'),
        ),
    ]
