# Generated by Django 6.1 on 2026-08-11 19:34

import myapp.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_herovideo_video_alter_offer_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 recommended.', null=True, storage=myapp.cloudinary_storage.SmartVideoCloudinaryStorage(), upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='video',
            field=models.FileField(blank=True, null=True, storage=myapp.cloudinary_storage.SmartVideoCloudinaryStorage(), upload_to='offers/videos/'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=myapp.cloudinary_storage.SmartVideoCloudinaryStorage(), upload_to='portfolio/videos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, storage=myapp.cloudinary_storage.SmartVideoCloudinaryStorage(), upload_to='services/'),
        ),
    ]
