# Generated by Django 6.1 on 2026-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_herovideo_video_alter_offer_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-is_developer', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Mark this member as the site Developer. Only one Developer is allowed at a time.'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_developer', True)), fields=('is_developer',), name='single_developer'),
        ),
    ]
