# Generated by Django 6.1 on 2026-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_teammember_options_teammember_is_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='When enabled, visitors see a maintenance screen across the whole site. Admins stay logged in and can switch it back off.'),
        ),
    ]
