# Generated by Django 6.1 on 2026-08-13 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sitevisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['-last_seen'], 'verbose_name': 'Site visitor', 'verbose_name_plural': 'Site visitors'},
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='path',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='device_type',
            field=models.CharField(blank=True, default='', help_text='Mobile / Tablet / Desktop', max_length=20),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='os',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='screen',
            field=models.CharField(blank=True, default='', help_text='Screen resolution, e.g. 1920x1080', max_length=40),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='First visit time'),
        ),
    ]
