# Generated by Django 6.1 on 2026-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_sitevisit_options_remove_sitevisit_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', 'Critical'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, default='ERROR', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Short, human-readable description.')),
                ('traceback', models.TextField(blank=True, help_text='Full Python traceback, when available.')),
                ('path', models.CharField(blank=True, default='', help_text='URL that triggered the error.', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.CharField(blank=True, default='', help_text='Logged-in username, if any.', max_length=150)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Error log',
                'verbose_name_plural': 'Error logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
