# Generated by Django 6.1 on 2026-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='body_font',
            field=models.CharField(choices=[("Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Manrope'), ('Poppins, -apple-system, BlinkMacSystemFont, sans-serif', 'Poppins'), ('Inter, -apple-system, BlinkMacSystemFont, sans-serif', 'Inter'), ('Jost, -apple-system, BlinkMacSystemFont, sans-serif', 'Jost'), ("'Nunito Sans', -apple-system, BlinkMacSystemFont, sans-serif", 'Nunito Sans'), ("Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Montserrat'), ("'Open Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Open Sans'), ("Lato, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Lato'), ("Raleway, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Raleway'), ("'Work Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Work Sans'), ("'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Plus Jakarta Sans'), ("Outfit, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Outfit'), ("Mulish, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Mulish')], default="Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", max_length=200),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='heading_font',
            field=models.CharField(choices=[("'Playfair Display', Georgia, serif", 'Playfair Display'), ("'Cormorant Garamond', Georgia, serif", 'Cormorant Garamond'), ("'Marcellus', Georgia, serif", 'Marcellus'), ("'Libre Baskerville', Georgia, serif", 'Libre Baskerville'), ("'EB Garamond', Georgia, serif", 'EB Garamond'), ("'Cinzel', Georgia, serif", 'Cinzel'), ("'Bodoni Moda', Georgia, serif", 'Bodoni Moda'), ("'Fraunces', Georgia, serif", 'Fraunces'), ("'Prata', Georgia, serif", 'Prata'), ("'Italiana', Georgia, serif", 'Italiana'), ("'Lora', Georgia, serif", 'Lora'), ("'Josefin Sans', 'Segoe UI', sans-serif", 'Josefin Sans'), ("'Tenor Sans', 'Segoe UI', sans-serif", 'Tenor Sans')], default="'Playfair Display', Georgia, serif", max_length=200),
        ),
    ]
