# Generated by Django 6.1 on 2026-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_themesettings_body_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', help_text='Portrait = zumwa (9:16, phone video). Landscape = wide (16:9). Hero usko bina crop ke sahi style me dikhayega.', max_length=20),
        ),
    ]
