# Generated by Django 6.1 on 2026-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_herovideo_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='body_font',
            field=models.CharField(choices=[("Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Manrope'), ('Inter, -apple-system, BlinkMacSystemFont, sans-serif', 'Inter'), ("'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Plus Jakarta Sans'), ("Outfit, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Outfit'), ("Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Montserrat'), ('Poppins, -apple-system, BlinkMacSystemFont, sans-serif', 'Poppins')], default="Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", max_length=200),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='heading_font',
            field=models.CharField(choices=[("'Playfair Display', Georgia, serif", 'Playfair Display'), ("'Cormorant Garamond', Georgia, serif", 'Cormorant Garamond'), ("'Fraunces', Georgia, serif", 'Fraunces'), ("'Libre Baskerville', Georgia, serif", 'Libre Baskerville'), ("'Marcellus', Georgia, serif", 'Marcellus'), ("'Montserrat', 'Segoe UI', sans-serif", 'Montserrat')], default="'Playfair Display', Georgia, serif", max_length=200),
        ),
    ]
