# Generated by Django 6.1 on 2026-09-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_map_retired_fonts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Only today or a future date.', unique=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], db_index=True, default='BOOKED', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, help_text='Internal note, never shown publicly.', max_length=300)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='myapp.service')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
